# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hacklabjkl
      POSTGRES_PASSWORD: HacklabIsGreat123
